apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: HPA-shifts
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dp-shitfs
  targetCPUUtilizationPercentage: 70

