apiVersion: apps/v1
kind: Deployment
metadata:
  name: dp-users
spec:
  replicas: 1
  selector:revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: app-users
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: app-users
    spec:
      containers:
      - name: app-users
        image: docker.io/httpd:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: svc-users
spec:
  type: LoadBalancer
  selector:
    app: app-users
  ports:
  - port: 8080
    targetPort: 8080
